ifndef CONFIG_ARCH_MESON64_ODROID_COMMON
dtb-y += g12a_s905d2_skt.dtb
dtb-y += g12a_s905d2_skt_buildroot.dtb
dtb-y += g12a_s905d2_u200.dtb
dtb-y += g12a_s905d2_u200_buildroot.dtb
dtb-y += g12a_s905d2_u200_drm_buildroot.dtb
dtb-y += g12b_a311d_w400.dtb
dtb-y += g12b_a311d_w400_buildroot.dtb
endif
dtb-$(CONFIG_ARCH_MESON64_ODROIDC4) += meson64_odroidc4.dtb
dtb-$(CONFIG_ARCH_MESON64_ODROIDC4) += meson64_odroidhc4.dtb
dtb-$(CONFIG_ARCH_MESON64_ODROIDN2) += meson64_odroidn2.dtb
dtb-$(CONFIG_ARCH_MESON64_ODROIDN2) += meson64_odroidn2_plus.dtb
dtb-$(CONFIG_ARCH_MESON64_ODROIDN2) += meson64_odroidn2_drm.dtb

subdir-$(CONFIG_ARCH_MESON64_ODROIDC4) += overlays/odroidc4
subdir-$(CONFIG_ARCH_MESON64_ODROIDN2) += overlays/odroidn2

dtb-y += sm1_s905x3_ac214.dtb
dtb-y += sm1_s905x3_2g_1gbit.dtb
dtb-y += sm1_s905x3_2g.dtb
dtb-y += sm1_s905x3_4g_1gbit.dtb
dtb-y += sm1_s905x3_4g.dtb
dtb-y += sm1_s905x3_beelink_gt1mini2_2g.dtb
dtb-y += sm1_s905x3_beelink_gt1mini2_4g.dtb
dtb-y += sm1_s905x3_odroid_c4.dtb
dtb-y += sm1_s905x3_odroid_hc4.dtb
